# Markdown file to only look at summary.json files

In [38]:
DEFAULT_SUMMARY_PATH = "//dartfs/rc/lab/B/BhattacharyaI/Results/nnUNet_data/nnUNet_results/{input_dataset}/autoPET3_Trainer__nnUNetResEncUNetLPlansMultiTalent__3d_fullres/{fold}/{validation}/summary.json"

import pandas as pd

path_902 = DEFAULT_SUMMARY_PATH.format(input_dataset="Dataset902_AutoPet", fold="{fold}", validation="{validation}")
path_903 = DEFAULT_SUMMARY_PATH.format(input_dataset="Dataset903_AutoPet", fold="{fold}", validation="{validation}")
path_901 = DEFAULT_SUMMARY_PATH.format(input_dataset="Dataset901_AutoPet", fold="{fold}", validation="{validation}")

def read_summary_file(path, fold, validation): 
    import json
    with open(path.format(fold=fold, validation=validation), "r") as f:
        return json.load(f)

f902_0 = read_summary_file(path_902, fold="fold_0", validation="validation")
f902_1 = read_summary_file(path_902, fold="fold_1", validation="validation_279")
f902_2 = read_summary_file(path_902, fold="fold_2_first", validation="validation_279")

f903_0 = read_summary_file(path_903, fold="fold_0", validation="validation_279")
f903_1 = read_summary_file(path_903, fold="fold_1", validation="validation_279")

f901_6 = read_summary_file(path_901, fold="fold_6", validation="validation_with_mirror")
f901_7 = read_summary_file(path_901, fold="fold_7", validation="validation_with_mirror")
f901_8 = read_summary_file(path_901, fold="fold_8", validation="validation")
# f901_9 = read_summary_file(path_901, fold="fold_9")
# f901_10 = read_summary_file(path_901, fold="fold_10")

# get variable name of f0 
summary_files = [f902_0, f902_1, f902_2, f903_0, f903_1, f901_6, f901_7, f901_8]
names = ["f902_0", "f902_1", "f902_2", "f903_0", "f903_1", "f901_6", "f901_7", "f901_8"]
names_dict= {
    "f902_0": "active learning 1% (no tta)",
    "f902_1": "active learning 1% with 15% pseudo labels (tta)",
    "f902_2": "active learning 1% with 30% pseudo labels (tta)",
    "f903_0": "active_learning 5% (tta)",
    "f903_1": "active_learning 5% with 15% pseudo labels (tta)",
    "f901_6": "All of the pseudo labels (tta)",
    "f901_7": "15% pseudo labels (tta)",
    "f901_8": "30% pseudo labels (no tta)"
}

names = [names_dict[name] for name in names]
dfs = []

for i, summary_file in enumerate(summary_files):
    df = pd.DataFrame(summary_file['foreground_mean'], index=[0]).round(3)
    df["fold"] = names[i]
    dfs.append(df)

summary_df = pd.concat(dfs, ignore_index=True)
# make fold the first column 
cols = summary_df.columns.tolist()
cols = cols[-1:] + cols[:-1]
summary_df = summary_df[cols]
summary_df.sort_values('Dice')

,fold,Dice,FN,FP,IoU,TN,TP,n_pred,n_ref
6,15% pseudo labels (tta),0.576,3030.919,2926.045,0.456,4.045680e+07,6227.340,9153.385,9258.259
1,active learning 1% with 15% pseudo labels (tta),0.589,3229.960,2558.648,0.466,4.045717e+07,6028.300,8586.947,9258.259
2,active learning 1% with 30% pseudo labels (tta),0.590,3244.652,2555.502,0.466,4.045717e+07,6013.607,8569.109,9258.259
4,active_learning 5% with 15% pseudo labels (tta),0.591,2998.583,2229.854,0.475,4.045749e+07,6259.676,8489.530,9258.259
0,active learning 1% (no tta),0.607,3105.235,2364.316,0.486,4.045736e+07,6153.024,8517.340,9258.259
7,30% pseudo labels (no tta),0.615,2516.854,2574.895,0.496,4.045715e+07,6741.405,9316.300,9258.259
3,active_learning 5% (tta),0.630,2730.271,2171.259,0.510,4.045755e+07,6527.988,8699.247,9258.259
5,All of the pseudo labels (tta),0.634,1571.648,3901.372,0.514,4.045582e+07,7686.611,11587.984,9258.259

In [25]:
path_999_old = DEFAULT_SUMMARY_PATH.format(input_dataset="Dataset999_AutoPet", fold="other_splits/{fold}")

fold_1 = read_summary_file(path_999_old, fold="fold_1_ens_0")
fold_5 = read_summary_file(path_999_old, fold="fold_5_original")
fold_20 = read_summary_file(path_999_old, fold="fold_20")
fold_30 = read_summary_file(path_999_old, fold="fold_30")
names_999 = ["fold_1_ens_0", "fold_5_original", "fold_20", "fold_30"]
names_999_dict = {
    "fold_1_ens_0": "1% Pseudo labels",
    "fold_5_original": "5% Pseudo labels",
    "fold_20": "20% Pseudo labels",
    "fold_30": "30% Pseudo labels"
}

# make dataframe for fold_1, fold_5, fold_20, fold_30
dfs_999 = []
for i, fold in enumerate([fold_1, fold_5, fold_20, fold_30]):
    df = pd.DataFrame(fold['foreground_mean'], index=[0]).round(3)
    df["fold"] = names_999_dict[names_999[i]]
    dfs_999.append(df)
summary_df_999 = pd.concat(dfs_999, ignore_index=True)
# make fold the first column
cols = summary_df_999.columns.tolist()
cols = cols[-1:] + cols[:-1]
summary_df_999 = summary_df_999[cols]
summary_df_999.sort_values('Dice')

,fold,Dice,FN,FP,IoU,TN,TP,n_pred,n_ref
0,1% Pseudo labels,0.347,7540.190,744.024,0.246,4.045898e+07,1718.069,2462.093,9258.259
1,5% Pseudo labels,0.469,4427.312,1883.773,0.358,4.045784e+07,4830.947,6714.721,9258.259
3,30% Pseudo labels,0.594,3352.563,1606.526,0.478,4.045812e+07,5905.696,7512.223,9258.259
2,20% Pseudo labels,0.611,3242.676,1942.340,0.489,4.045778e+07,6015.583,7957.923,9258.259